# Generated by Django 4.2 on 2023-04-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='mobilenumber',
            field=models.IntegerField(),
        ),
    ]
